### ISSUE TITLE
Typed array validation containing undefined values succeeds

### ISSUE THREAD

**Issue by n1k0** [tdegrunt/jsonschema#206] opened 2017-02-17 10:39 UTC
```js
> js = require("jsonschema")
{ Validator: [Function: Validator],
  ValidatorResult: [Function: ValidatorResult],
  ValidationError: [Function: ValidationError],
  SchemaError: [Function: SchemaError],
  validate: [Function] }
> js.validate([1, undefined, 3], {type:"array", items:{type:"integer"}}).errors
[]
```

No errors. It seems the lib treats `undefined` as a possible integer, which is strange and highly surprising to me. It sounds like a bug, but I'm not sure if the JSON schema spec would just allow that.

FWIW, [jsonvalidator.net](http://www.jsonschemavalidator.net/) raises a validation error with this example:

![](http://i.imgur.com/FyzGFgG.png)

It may be because `undefined` doesn't exist in JSON land, as serialization will always convert them to `null`, which pass validation. It's up to you to decide if you want to support js values (here `undefined`) along JSON ones (but in any case users should be explicitly warned about it in the docs).

**Comment by awwright** [comment] 2020-08-27 01:30
This seems to be a duplicate of #211, if you have any further questions feel free to comment there, or open a new issue.

**Closed by awwright** 2020-08-27 01:30 UTC
