### ISSUE TITLE
Uncaught exception when type=[null] is used

### ISSUE THREAD

**Issue by rweigel** [tdegrunt/jsonschema#220] opened 2017-07-05 21:54 UTC
In the following schema,`null` was used in the type array (this is not a valid JSON schema - `"null"` should have been used).  This causes an uncaught exception when attempting to validate in jsonschema 1.1.1 using node v4.2.6:

```
node_modules/jsonschema/lib/attribute.js:50
      return v.id && ('<' + v.id + '>') || (v+'');
              ^
TypeError: Cannot read property 'id' of null
```

```javascript
var json =
{
	"parameters":
		[
			{ 
				"fill": -1e31
			}
		]
}

var schema =
{
		"type": "object",
		"properties": {
			"parameters": {
				"description": "Parameters in dataset",
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"fill": {
							"type": ["string",null]
						}
					}
				}
			}
		}
	}

var Validator = require('jsonschema').Validator;
var v = new Validator();
v.validate(json, schema);
```

**Comment by awwright** [comment] 2017-07-11 21:33
What would be the expected behavior, do you think?
They only thing I can think of doing would be throwing a slightly different
exception.

**Comment by rweigel** [comment] 2017-07-12 01:27
An "invalid schema" error and an indication of the offending location would be ideal.  Perhaps one could validate the input schema against a meta-schema (https://github.com/json-schema-org/json-schema-spec)?

**Comment by awwright** [comment] 2018-03-15 04:15
Ok.
Some basic schema validation could be implemented during the scanning phase, probably. I'll note it as a feature request, since technically this is a user error.

**Comment by awwright** [comment] 2020-10-09 21:29
This should be fixed in 27cc3a5239e1922ce61f2880d5ec96b592e819b2

**Closed by awwright** 2020-10-09 21:29 UTC
Labels: bug
