### ISSUE TITLE
Custom error message with properties

### ISSUE THREAD

**Issue by moatazelmasry2** [tdegrunt/jsonschema#139] opened 2015-08-16 09:58 UTC
Hi,

I couldn't find a possibility to add a custom error message when a property is invalid, example: 

``` json
schema = {
    "properties": {
        "mobile": {"type": "string", "minimum" : 4, "pattern": "^00[0-9]{2,18}", "message" : "bad mobile"}}
    }
}

instance = { "mobile": "0123456"}
```

AFAIK this feature is not part of the schema, but would it be interesting to add it? I can submit a pull request to that

Regards,
Moataz

**Comment by Acubed** [comment] 2015-08-16 17:29
Sometimes I add a "label" or "description" property to schemas, but this
isn't exactly the same thing. And they're only for internal usage, since
it's in a single language and not localized.

For this reason, it might be better to expose which schema it is that
failed (returning its URI). Then you can catch the error and map it to an
error message appropriate for the particular user and UI.

We already return the property/instance path that failed, so that shouldn't
be too hard.

**Comment by awwright** [comment] 2020-10-06 21:32
This seems like a duplicate of #212 and some other issues about localizing error messages, so I'm going to close this out.

If you have any further questions, please feel free to comment or open a new issue.

**Closed by awwright** 2020-10-06 21:32 UTC
