### ISSUE TITLE
oneOf not properly supported

### ISSUE THREAD

**Issue by g-liu** [tdegrunt/jsonschema#196] opened 2017-01-13 00:09 UTC
Given this schema `schema`:

```json
{
    "title": "schema",
    "type": "object",
    "properties": {
        "id": {
            "oneOf": [{
                "type": "string",
                "minLength": 1
            }, {
                "type": "null"
            }]
        }
    }
}
```

and this JSON `json`:

```json
{"id": "not-null"}
```

calling `validate(json, schema, {throwError: true})` claims that the JSON fails against the schema:

```
instance.id is not of a type(s) null
```

However the schema clearly states that `id` has to be exactly one of `string` with nonzero length or `null`. `instance.id` is a `string` of nonzero length, and not a `null`. Therefore it should satisfy the schema.

**Comment by g-liu** [comment] 2017-01-13 00:19
I may be misunderstanding the purpose of `options.throwError`. When `validate` function throws an error, does it necessarily mean that there is an error with the validation of the data against the schema? In the above case:

```javascript
validate(json, schema).valid // => true
validate(json, schema).errors // => []
```

**Comment by awwright** [comment] 2017-04-13 21:39
This seems to be an issue with throwError which is largely experimental. I'll close this as a duplicate of #119, but feel free to provide additional information and feedback.

**Closed by awwright** 2017-04-13 21:39 UTC
