### ISSUE TITLE
feature:  built library uncoupled from node

### ISSUE THREAD

**Issue by gregglind** [tdegrunt/jsonschema#197] opened 2017-01-13 15:43 UTC
For REASONS*, I would like to have a built version of this that uncouples from node.  As near as I can tell, the only node thing is `URL` .  I attempted to solve this by using `JSV` and `json-schema`, but both have inconsistent `jsonschema v4` support.  

I THINK a webpacked  version of the lib would work, but I will my theory to the test :)

*(Using it inside Firefox addons, but there are probably other real cases)

**Comment by awwright** [comment] 2020-10-06 01:01
I'm going to close this as a duplicate of #18 — I think this issue would be resolved by #18, but please let me know if that's not the case.

**Closed by awwright** 2020-10-06 01:01 UTC
