### ISSUE TITLE
ValidationError not instanceof Error

### ISSUE THREAD

**Issue by grindfuk** [tdegrunt/jsonschema#105] opened 2015-01-21 15:13 UTC
Hi! 
Great package. I'm  new to node.js and I am using this package all the time now. 

So, if you do:

```
> js = require('jsonschema')
> new js.SchemaError() instanceof  Error
true
> new js.ValidationError() instanceof Error
false
```

Just wondering if this is by design or in the plans for changing or if I am missing something somewhere (Sorry if this is the case).

**Comment by Acubed** [comment] 2015-01-21 15:22
A ValidationError isn't an object that's thrown, it just contains details about a particular problem with your instance. There could be several of them all at once, they're all returned in a ValidatorResult object.

I suppose one might find a reason to throw a ValidationError, is that what you want to do?

Does that answer your question?

**Comment by grindfuk** [comment] 2015-01-21 15:35
Oh I see! Thanks for answering so quickly.

The ValidationError is added to the ValidatorResult but if the option `{throwError: true}` is set, the first 
ValidationError is thrown but not as an Error Object. Would it be worth it to add an option to the constructor to initialize it as an object? 
```
var ValidationError = exports.ValidationError = function ValidationError (message, instance, schema, propertyPath, options) {
...
  if (options && options.throwError) {
    Error.call(this, message);
    Error.captureStackTrace(this, ValidationError);
  }
}
```
I'm asking mainly because using promise/deferred methods usually catch `instanceof Error`. I think I have a custom solution but I thought it would be cool to reach out to you.

**Comment by Acubed** [comment] 2015-05-14 05:18
Ah ok. That might be a good excuse to inherit from Error.

Or, create a separate type of object for the error itself, and it contains a ValidationError instance.

I'll take a look.

**Comment by awwright** [comment] 2020-10-17 07:09
I'm going to close this as a duplicate of #264, which should solve this issue. Please drop a comment if there's anything missing in that issue.

**Closed by awwright** 2020-10-17 07:09 UTC
Labels: bug
