### ISSUE TITLE
Reports wrong type: "is not of a type(s) [object Object]"

### ISSUE THREAD

**Issue by xerosugar** [tdegrunt/jsonschema#349] opened 2021-07-30 09:33 UTC
```
module.exports = class String {
    static getSchema() {
        return {
            type: "string",
            minLength: 1
        };
    }
};

module.exports = class UsesString {
    static getSchema() {
        return {
            type: String.getSchema(),
        };
    }
};
```
When the wrong type is used and validated with UsesString like `const result = validator.validate(1, UsesString.getSchema());`
The error message becomes: `is not of a type(s) [object Object]` when you expect it to be `is not of a type(s) string`.

**Comment by awwright** [comment] 2021-07-30 18:41
What is the behavior that you expect?

You're providing an object as the value for the "type" keyword, which gets cast to a string. Since that string `[object Object]` is not one of the known types, it fails.

**Comment by xerosugar** [comment] 2021-08-02 09:16
I wanted the type to be read from the String class, so I guess I should've done this instead: `type: String.getSchema().type`.

**Comment by awwright** [comment] 2021-08-02 18:23
@xerosugar If there's nothing left here to solve then please close this out. Otherwise please provide an example of the expected behavior.

**Closed** 2021-08-02 19:20 UTC
