### ISSUE TITLE
oneOf with required fields does not work correctly.

### ISSUE THREAD

**Issue by eavdmeer** [tdegrunt/jsonschema#235] opened 2017-10-26 12:40 UTC
I want to validate that a simple object contains an Underlying field that either has an InstrumentISIN or an InstrumentLEI field. This is the schema:

```javascript
var schema = {
  "type": "object",
  "properties": {
    "Underlying": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "InstrumentISIN": { "type": "string" }
          },
          "required": [ "InstrumentISIN" ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "InstrumentLEI": { "type": "string" }
          },
          "required": [ "InstrumentLEI" ],
          "additionalProperties": false
        }
      ]
    }
  }
};
```

The object I'm validating is:

```javascript
var record = {
  "Underlying": {
    "InstrumentISIN": "FR0010138487"
  }
};
```

This result in the following error:

`instance.Underlying requires property "InstrumentLEI"
`

Changing the record to include an InstrumentLEI instead of an InstrumentISIN predictably results in:

`instance.Underlying requires property "InstrumentISIN"`

Let's put both in:

```javascript
var record = {
  Underlying: {
    InstrumentLEI: "FR0010138487",
    InstrumentISIN: "FR0010138487"
  }
};
```

This correctly gives:

`instance.Underlying additionalProperty "InstrumentLEI" exists in instance when not allowed`

Validating the schema and data in https://json-schema-validator.herokuapp.com/ works as expected.

**Comment by NeoN0x** [comment] 2017-11-12 18:43
I got the same issue.

This is related to this pull request #174 .

Hope it will be merged.

**Comment by tdegrunt** [comment] 2017-11-12 19:26
I’m for merging, though I saw that the pull request has merge conflicts/issues. If those get resolved I’ll merge and push a new version.  

I can’t spend time on this myself right now due to personal situation.  

Cheers,  
Tom

**Comment by awwright** [comment] 2018-03-15 01:44
@eavdmeer I can't reproduce this, can you test this against master branch?

```
{
  "Underlying": {
    InstrumentLEI: "FR0010138487",
    InstrumentISIN: "FR0010138487"
  }
}
```

This produces `instance.Underlying is not exactly one from [subschema 0],[subschema 1]`



```
{
  "Underlying": {
    InstrumentLEI: "FR0010138487"
  }
}
```
This validates

**Comment by awwright** [comment] 2020-09-26 04:49
Closing for inactivity. If this is still causing a problem, please feel free to file a new issue. Please include sample code with expected and actual output.

**Closed by awwright** 2020-09-26 04:49 UTC
