### ISSUE TITLE
doc request:  options and how to use throwError

### ISSUE THREAD

**Issue by gregglind** [tdegrunt/jsonschema#193] opened 2016-12-21 15:35 UTC
In the README, throwError is menitoned.  A short example showing how to invoke it Would Be Nice If.

```
// 'a' isn't a number 
 console.log(v.validate('a', {"type": "number"}, {throwError: true}));

vs.

 console.log(v.validate('a', {"type": "number"}));
```

Justification:
- it took me a while to find a code example.
- it's totally awesome that you have both throw style and list of errors style, and I want to show off your caring attention to detail!

**Comment by awwright** [comment] 2016-12-21 18:51
If I recall correctly, throwError isn't well tested (there's some cases
where it does unexpected things or throws when it shouldn't), so I'll
probably try to add some tests around that first.

**Comment by awwright** [comment] 2017-04-13 21:25
Multiple people are having this issue, I'll close this as a duplicate of #119

**Closed by awwright** 2017-04-13 21:25 UTC

**Comment by SalmaTofaily** [comment] 2019-08-09 11:34
Yes, it did not work with me. 
Documentation about options is sparse, took time just to figure out the code exmaple.
