### ISSUE TITLE
Even with options.throwError false, validation throws when enum is not an array

### ISSUE THREAD

**Issue by mauritslamers** [tdegrunt/jsonschema#178] opened 2016-06-20 11:19 UTC
When an error is made in the schema, and enum is not an array, the validation throws an error.
It also throws an error when the validation function is called with options.throwError set to false.

**Comment by awwright** [comment] 2017-04-13 21:26
This seems to be a duplicate of #119.
Please let us know if your situation differs!

**Closed by awwright** 2017-04-13 21:26 UTC
